### ISSUE TITLE
Make the compiled Excel Addin configurable via a Config file

### ISSUE THREAD

**Issue by asndev** [PATRONAS/opuxl#1]
current:
- different properties are hardcoded

target:
- IP, Port, Function Prefix should be configurable by a config file which should be placed next to the .XLL file.

Eg.: config.ini

```
ip=127.0.0.1
port=56789
prefix=Opus
```

**Comment by asndev** [comment]
commit: 61e9f7879a42b32cc354fefd1afe97d784750ac9

**Comment by rpseng** [comment]
How this config actually works? One create a config file named Opuxl.xll.config along with (same folder) as the xll? Further, the option to change the prefix apparently was not included.

Thanks .
