### ISSUE TITLE
Does not work with Excel 2010 32-bit

### ISSUE THREAD

**Issue by celxa** [PATRONAS/opuxl#4]
I downloaded 2 files below
https://github.com/PATRONAS/opuxl/raw/master/opuxl_addin/Opuxl/OpuxlClassLibrary/Opuxl.xll
https://github.com/PATRONAS/opuxl/raw/master/opuxl_addin/Opuxl/OpuxlClassLibrary/Opuxl.dna

Installed Opuxl.xll add-in, the add-in appeared in the add-in list and was activated/ticked

Closed Excel

Started Java DemoServer

Console showed "[Thread-0] INFO de.patronas.opus.opuxl.server.OpuxlServer - Opuxel Server Socket startet on port: 61379"

Started Excel, Opus functions weren't registered, =Opus.GetSeries(3) returns #NAME?

Java process was OK, I was able to telnet to 127.0.0.1:61379, so it looks like the add-in couldn't create a connection

**Comment by asndev** [comment]
Hi celxa,

the .xll file in /Opuxl/OpuxlClassLibrar/Opuxl.xll is not the compiled Excel addin; it is a "source" xll (containing ExcelDNA stuff) which is used to generated the Excel Addin.
The final Excel addin has to be compiled using Visual Studio.

I've done that for the current version and you can find the compiled & packed addin for 32bit & 64bit here: https://github.com/PATRONAS/opuxl/releases/tag/v1.0
