### ISSUE TITLE
Add support for non-Excel objects

### ISSUE THREAD

**Issue by celxa** [PATRONAS/opuxl#5]
Excel returns "Error while executing Function" if the Java function returns a Java object.

XLLOOP supports object handles, so that objects can be used as arguments for other functions.

Is it possible for opuxl to support that too?

**Comment by asndev** [comment]
Currently, Opuxl requires the incoming data to be in a specified format ([ResponsePayload](https://github.com/PATRONAS/opuxl/blob/master/opuxl_addin/Opuxl/ClientConnector/communication/ResponsePayload.cs))

It is possible to use opuxl functions as arguments for other functions, if you reference the corresponding cell, eg (assume those functions are defined):
- in Cell E10: =Opuxl.GetRandomNumber()
- in Cell E11: =Opuxl.Pow(E10)

Can you share an example for the xlloop object handle use case?

**Comment by celxa** [comment]
What I mean is that if I have two functions below:
`List f()`
`OpuxlMatrix g(List)`

I can't pass the result of f() to g()

xlloop example: http://xlloop.sourceforge.net/lisphandler.html
That page is also mentioned in https://github.com/poidasmith/xlloop/issues/2

**Comment by asndev** [comment]
Well, the lisphandler exposes an 'eval' function that does the magic. It will take the incoming message from Excel, evaluate it within lisp and then just return the result.

Such an 'eval' function would be also possible for Opuxl: just create an eval method within your server (eg Java, or JavaScripts eval(...)) where you evaluate the incoming message via reflection and then just return the result wrapped in an Opuxl Matrix. (feel free to send a PR)

Currently, the addin is built to only display Excel values to have a well defined api between Excel and the Server. We could check within the C# code whether the incoming result is an Opuxl Type, or just a plain object and then use the correct display mechanism - but that is currently not on our roadmap.
